eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: producto
          uri: http://localhost:8090
          predicates:
            - Path=/api/producto/**
        - id: categoria
          uri: http://localhost:9090
          predicates:
            - Path=/api/categoria/**